#!/bin/sh
echo -n "What should I do --- (Y)es/(N)o/(C)ontinue? [Y] "
read answer
case $answer in
	y|Y|"")
		echo "YES"
	;;
	c|C)
		echo "CONTINUE"
	;;
	N|n)
		echo "no"
	;;
	*)
		echo "UNKNOWN"
	;;
esac
	
